<?php
/**
 * Coditron
 *
 * @category  Coditron
 * @package   Coditron_OTPVerification
 * @author    Coditron
 * @copyright Copyright (c) Coditron (https://coditron.com)
 */
?>
<tr id ="row_CT_magebarcodeinventory_information_author">
    <td colspan="4">
        <h4>
            <p>
                <?= $escaper->escapeHtml(__('Author:')); ?> 
                <a target="_blank"
                    title="<?= $escaper->escapeHtml(__('Coditron Software Private Limited'));?>"
                    href="<?= $escaper->escapeUrl("https://coditron.com/");?>" >
                <?= $escaper->escapeHtml(__('coditron'));?></a>
            </p>
        </h4>
    </td>
</tr>
